version: "3.8"

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: votes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - redis
      - db
    networks:
      - poll-tier
    restart: on-failure

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: on-failure

  worker:
    build: ./worker
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: votes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - redis
      - db
    networks:
      - back-tier
    restart: on-failure

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes
    ports:
      - "5432:5432"
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: on-failure

  result:
    build: ./result
    ports:
      - "5001:80"
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: votes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - redis
      - db
    networks:
      - back-tier
      - result-tier
    restart: on-failure

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
